// seedFoodItems.js

const mongoose = require("mongoose");
const FoodItem = require("./Food_items");

mongoose
  .connect("mongodb+srv://CanteenManagementSystem:nNu0jGhuF4Bg0tpu@cluster0.btxksx4.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0", {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  })
  .then(async () => {
    console.log("✅ MongoDB connected");

    // Clear existing food items (optional)
    await FoodItem.deleteMany({});
    console.log("🧹 Old food items cleared");

    const sampleFoodItems = [
      {
        food_id: "F013",
        name: "Chicken Biryani",
        description: "Spicy basmati rice with tender chicken",
        price: 149.99,
        image_url: "https://ministryofcurry.com/wp-content/uploads/2024/06/chicken-biryani-5.jpg",
        available_qty: 40,
        category: "Meals",
        rating: 4.6,
        reviews_count: 120,
        created_at: new Date(),
      },
      {
        food_id: "F007",
        name: "Masala Dosa",
        description: "South Indian dish with sambhar",
        price: 85.0,
        image_url: "https://delishglobe.com/wp-content/uploads/2024/09/Masala-dosa-1-500x500.png",
        available_qty: 25,
        category: "Meals",
        rating: 4.3,
        reviews_count: 50,
        created_at: new Date(),
      },
      {
        food_id: "F014",
        name: "Butter Chicken",
        description: "Creamy chicken in rich tomato gravy",
        price: 159.0,
        image_url: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/07/chicken-butter-masala-recipe.jpg",
        available_qty: 20,
        category: "Meals",
        rating: 4.7,
        reviews_count: 90,
        created_at: new Date(),
      },
      {
        food_id: "F009",
        name: "Chocolate Shake",
        description: "Thick shake with cocoa",
        price: 70.0,
        image_url: "https://www.willcookforfriends.com/wp-content/uploads/2017/01/Decadent-Chocolate-Milkshake-Youd-Never-Know-Is-Healthy-hi-res-web-1B.jpg",
        available_qty: 60,
        category: "Beverages",
        rating: 4.5,
        reviews_count: 98,
        created_at: new Date(),
      },
      {
        food_id: "F006",
        name: "Paneer Roll",
        description: "Stuffed wrap with spicy paneer",
        price: 75.0,
        image_url: "https://www.vegrecipesofindia.com/wp-content/uploads/2017/01/paneer-kathi-roll-recipe-1.jpg",
        available_qty: 35,
        category: "Snacks",
        rating: 4.1,
        reviews_count: 38,
        created_at: new Date(),
      },
      {
        food_id: "F002",
        name: "Cheese Pizza",
        description: "Loaded with extra cheese",
        price: 129.99,
        image_url: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/10/00/dd/00/domino-s-pizza.jpg?w=600&h=-1&s=1",
        available_qty: 30,
        category: "Meals",
        rating: 4.5,
        reviews_count: 150,
        created_at: new Date(),
      },
      {
        food_id: "F015",
        name: "Egg Curry",
        description: "Boiled eggs in spicy gravy",
        price: 95.0,
        image_url: "https://www.whiskaffair.com/wp-content/uploads/2019/03/Chettinad-Egg-Curry-2-3.jpg",
        available_qty: 30,
        category: "Meals",
        rating: 4.2,
        reviews_count: 54,
        created_at: new Date(),
      },
      {
        food_id: "F012",
        name: "Pav Bhaji",
        description: "Spicy mashed vegetables with pav",
        price: 85.0,
        image_url: "https://www.cubesnjuliennes.com/wp-content/uploads/2020/07/Instant-Pot-Mumbai-Pav-Bhaji-Recipe.jpg",
        available_qty: 25,
        category: "Meals",
        rating: 4.5,
        reviews_count: 66,
        created_at: new Date(),
      },
      {
        food_id: "F004",
        name: "Veg Momos",
        description: "Steamed dumplings with chutney",
        price: 69.0,
        image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRAdIdvxNYjUli1uIozMTzeZ9jCaG2fZUl9uA&s",
        available_qty: 40,
        category: "Snacks",
        rating: 4.0,
        reviews_count: 45,
        created_at: new Date(),
      },
      {
        food_id: "F016",
        name: "Chicken Sandwich",
        description: "Grilled chicken with lettuce & mayo",
        price: 89.0,
        image_url: "https://theyummydelights.com/wp-content/uploads/2022/03/grilled-tandoori-chicken-sandwich.jpg",
        available_qty: 45,
        category: "Snacks",
        rating: 4.4,
        reviews_count: 61,
        created_at: new Date(),
      },
      {
        food_id: "F010",
        name: "Samosa",
        description: "Crispy triangle snack",
        price: 20.0,
        image_url: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/12/samosa-recipe.jpg",
        available_qty: 100,
        category: "Snacks",
        rating: 4.0,
        reviews_count: 120,
        created_at: new Date(),
      },
      {
        food_id: "F001",
        name: "Veg Burger",
        description: "Crispy and spicy patty",
        price: 59.99,
        image_url: "https://images.slurrp.com/prod/recipe_images/transcribe/snack/Vegetable-Burger.webp",
        available_qty: 50,
        category: "Snacks",
        rating: 4.2,
        reviews_count: 78,
        created_at: new Date(),
      },
      {
        food_id: "F005",
        name: "Chole Bhature",
        description: "North Indian favorite",
        price: 89.0,
        image_url: "https://upload.wikimedia.org/wikipedia/commons/9/9e/Chole_Bhature_from_Nagpur.JPG",
        available_qty: 20,
        category: "Meals",
        rating: 4.4,
        reviews_count: 65,
        created_at: new Date(),
      },
      {
        food_id: "F008",
        name: "Lemonade",
        description: "Fresh lemon with mint",
        price: 30.0,
        image_url: "https://i2.wp.com/lmld.org/wp-content/uploads/2022/04/Lemonade-4.jpg",
        available_qty: 80,
        category: "Beverages",
        rating: 4.2,
        reviews_count: 33,
        created_at: new Date(),
      },
      {
        food_id: "F003",
        name: "Cold Coffee",
        description: "Chilled with chocolate syrup",
        price: 49.99,
        image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIEmUmcMDRgoUIsE24O9ge9ys0owBHRsi5zw&s",
        available_qty: 100,
        category: "Beverages",
        rating: 4.6,
        reviews_count: 90,
        created_at: new Date(),
      },
      {
        food_id: "F011",
        name: "Idli Vada",
        description: "Idli + Vada combo with chutney",
        price: 60.0,
        image_url: "https://vaya.in/recipes/wp-content/uploads/2018/02/Idli-and-Sambar-1.jpg",
        available_qty: 0,
        category: "Meals",
        rating: 4.3,
        reviews_count: 45,
        created_at: new Date(),
      },
    ];

    await FoodItem.insertMany(sampleFoodItems);
    console.log("🍽️ Sample food items inserted successfully");

    mongoose.connection.close();
  })
  .catch((err) => {
    console.error("❌ MongoDB connection error:", err);
  });
